name: 🚀 Deploy Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Deploy to local repo
      - name: Deploy to Release Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: addons/FracturalCommons
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        run: |
          mkdir release
          mv addons/FracturalCommons release

      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: release
